#The hailstone sequence starting at a positive integer n. Is generated by following two simple rules:
# (1) If n even, the next number in the sequence is n/ 2. 
# (2) If n is odd, the next number in the sequence is 3*n+1 
# A recursive function hailstone (n) Which prints the hailstone sequence beginning at 1. Stop when the sequence reaches the number 1.

def generateHailstoneUsingRecursion(n):
    if n == 1:
        return 1
    elif n%2 ==0:
        print(int(n), end=",")
        return generateHailstoneUsingRecursion(n / 2)
    else:
        print(int(n), end=",")
        return generateHailstoneUsingRecursion(3 * n + 1)
    

print("Enter a number to generate Hailstone Sequence: ")
number = int(input())

generateHailstoneUsingRecursion(number)